prometheus_sim:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    torso_yaw_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: torso_yaw_joint
      pid: {p: 100.0, i: 50.0, d: 10.0}

    torso_pitch_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: torso_pitch_joint
      pid: {p: 100.0, i: 50.0, d: 10.0}

    right_DOF1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_DOF1_joint
      pid: {p: 100.0, i: 1.0, d: 10.0}

    right_DOF2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_DOF2_joint
      pid: {p: 100.0, i: 1.0, d: 10.0}

    right_DOF3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_DOF3_joint
      pid: {p: 100.0, i: 1.0, d: 10.0}

    right_DOF4_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_DOF4_joint
      pid: {p: 100.0, i: 1.0, d: 10.0}

    right_DOF5_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_DOF5_joint
      pid: {p: 100.0, i: 1.0, d: 10.0}

    right_DOF6_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_DOF6_joint
      pid: {p: 100.0, i: 1.0, d: 10.0}

